language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git

install: |
  sudo apt-get install -y gettext libncurses5-dev libacl1-dev libgpm-dev
  git clone https://github.com/vim/vim /tmp/vim
  saved_pwd=`pwd`
  cd /tmp/vim
  version=v8.0.0237
  git checkout ${version}
  mkdir ~/bin
  ./configure --with-features=huge --enable-fail-if-missing --prefix=$HOME/bin/vim${version}
  make && make install
  export MY_VIM=$HOME/bin/vim${version}/bin/vim
  cd ${saved_pwd}

script: |
  ${MY_VIM} -Nu <(cat <<VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=.
  set rtp+=after
  filetype plugin indent on
  syntax enable
  VIMRC
  ) -c 'Vader! test/tscompletejob.vader' > /dev/null
